import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Aoboshi_One } from "next/font/google"; // ✅ add this
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const aoboshiOne = Aoboshi_One({
  variable: "--font-aoboshi",
  subsets: ["latin"],
  weight: "400", // optional, default 400
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${aoboshiOne.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
